fancybox: false ## If you want to use fancybox please set the value to true.

toc_number: false ## If you want to add list number to toc please set the value to true.

busuanzi: ## Busuanzi statistic
  site_enable: true ## Whether to enable site statistic.
  post_enable: false ## Whether to enable post statistic.

post_copyright:
  enable: true
  author: John

love: true ## If you want the love to appear when you click anywhere, set the value to true.

post_content_length: 180 ## Set the length of the post summary displayed on home page when no description written.

icp: 京ICP备xxxxxxxx号 ## China mainland only, show icp info on the bottom.
bei: 京公网安备xxxxxxxxxxxxxx号 ## China mainland only, show bei info on the bottom.

# The CDN provider for third-party scripts
cdn_type: unpkg ## Options: jsdelivr/fastly/unpkg/custom
cdn_custom_url: ## When cdn_type is 'custom', this is a required field. e.g. https://cdn1.yourdomain.com

# Site background image link
site_bg_img: /asset/img/bg6.webp

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Seven widgets in sidebar provided: search, info, category, tag, recent_posts, recent_comments and links.
  - search
  - info
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

info:
  avatar: /asset/img/avatar.jpg
  discription: Good good study, day day up.
  follow:
    enable: true
    icon: fa fa-github
    text: Follow Me
    link: https://github.com/guozhenyi/hexo-theme-clarity
  outlinkitem:
    - name: github # fa-{name}
      outlink: https://github.com/guozhenyi/hexo-theme-clarity
      message: Github
    - name: envelope
      outlink: mailto:admin@domain.com
      message: Email
      # color: '#007bff'
    - name: rss
      outlink: /atom.xml
      message: RSS
      # color: '#ff5722'

links:
  - title: 郭大侠的博客
    url: https://www.guozhenyi.com
    src: https://www.guozhenyi.com/favicon.ico
    desc: John's Blog

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

# Static files
js: js
css: css

# Theme version
version: 1.0.0
